set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(SDK_PATH "/sdk/PBSDK")

set(CMAKE_C_COMPILER "${SDK_PATH}/bin/arm-linux-gcc")
set(CMAKE_CXX_COMPILER "${SDK_PATH}/bin/arm-linux-g++")

set(CMAKE_FIND_ROOT_PATH "${SDK_PATH}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_C_FLAGS "-I${SDK_PATH}/include -I${SDK_PATH}/arm-linux/include" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "-I${SDK_PATH}/include -I${SDK_PATH}/arm-linux/include" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "-L${SDK_PATH}/lib -L${SDK_PATH}/arm-linux/lib" CACHE STRING "" FORCE)
